### ISSUE TITLE
Latest released emf2svg gem has platform `x64-unknown`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/emf2svg-ruby#14]
Instead, it should be `x64-mingw-ucrt`.

https://rubygems.org/gems/emf2svg/versions/1.1.0-x64-unknown
<img width="648" alt="Screenshot 2022-03-19 at 2 21 07 AM" src="https://user-images.githubusercontent.com/11865/159061111-e11732a3-f5e7-4735-86bd-7eaa5ef7d97b.png">

See:
https://rubygems.org/gems/pg/versions/1.3.0.rc2-x64-mingw-ucrt

<img width="718" alt="Screenshot 2022-03-19 at 2 20 44 AM" src="https://user-images.githubusercontent.com/11865/159061025-b7d02d10-056d-4068-8b2a-cd50a63375dc.png">

**Comment by maxirmx** [comment]
Yes, I am already fixing it
https://github.com/metanorma/emf2svg-ruby/commit/887327baa4f8910e491544a36c66a00c6c4d2d21

**Comment by maxirmx** [comment]
@ronaldtse  we now have version 1.1.1 with x64-nigw-ucrt platform
![1 1 1](https://user-images.githubusercontent.com/2081498/159079184-73f902a1-3873-4b99-acdb-2d1aabde3e1c.jpg)

I believe 1.1.0 may be removed if it is possible at all.

**Comment by ronaldtse** [comment]
@maxirmx all 1.1.0 yanked. Thanks!
<img width="458" alt="Screenshot 2022-03-19 at 11 43 23 AM" src="https://user-images.githubusercontent.com/11865/159105384-f3499690-bebb-4b76-a743-ea49853d6665.png">
