### ISSUE TITLE
Binary distribution does not work for packed-mn

### ISSUE THREAD

**Issue by maxirmx** [metanorma/emf2svg-ruby#24]
Binary distribution  that we have does not work for https://github.com/metanorma/packed-mn/issues/158
- it inherits expressir issue - https://github.com/lutaml/expressir/issues/106
- it requires additional shared libraries - https://github.com/metanorma/libemf2svg/issues/27

**Comment by ronaldtse** [comment]
Thank you @maxirmx for the great work!
