### ISSUE TITLE
Add tests for Ruby 3.0

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/emf2svg-ruby#27]
Right now the tests only run on Ruby 2.7 and 3.1 but not 3.0. Is there any difficulty adding 3.0? Just wanted to simplify the matrix. Thanks.

**Comment by maxirmx** [comment]
I think build script requires major rework. It looks like it was very simple in the beginning but  packaging and cross-compilation options made it messy.
Also it definitely lacks testing facilities as #28 shows. We just 'believe' that it packages and publishes correctly and considering ~10 packaging scenarios, it is risky IMHO
