### ISSUE TITLE
(URGENT) Crash with EMF file

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/emf2svg-ruby#30]
Just ran into this issue on Apple M1:

```sh
$ gem install emf2svg
Successfully installed emf2svg-1.4.1-arm64-darwin
1 gem installed
```

```sh
$ emf2svg images/image1.emf 
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.1-arm64-darwin/exe/emf2svg:7:in `write': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.1-arm64-darwin/exe/emf2svg:7:in `<top (required)>'
	from /Users/me/.rbenv/versions/3.1.1/bin/emf2svg:25:in `load'
	from /Users/me/.rbenv/versions/3.1.1/bin/emf2svg:25:in `<main>'
```

Two samples:
[image1.emf.zip](https://github.com/metanorma/emf2svg-ruby/files/8517628/image1.emf.zip)
[image2.emf.zip](https://github.com/metanorma/emf2svg-ruby/files/8517678/image2.emf.zip)

They look like this:
![image1](https://user-images.githubusercontent.com/11865/164132685-6c65dca4-75b9-4048-9fc5-22fd4d33aefd.png)

![image2](https://user-images.githubusercontent.com/11865/164132694-d3390554-c69f-42ed-aa2f-4f5da92c3510.png)

**Comment by maxirmx** [comment]
Usage:  emf2svg \<input filename\> \<output filename\>
No checks, if there is an issue with files, it crashes
Convertor itself works, you can use it with these two images

I will fix file processing

**Comment by ronaldtse** [comment]
Ahh. Can we add some usage instructions for the command line if the arguments are not provided? Thanks!

**Comment by maxirmx** [comment]
will do

**Comment by Intelligent2013** [comment]
Please add the attribute `viewBox` to correct svg rendering. Currently, even in the browser, svg doesn't render properly (cropped and wrong scale):
![image](https://user-images.githubusercontent.com/5559926/164202404-300a3bb8-75ad-4a15-9fba-664ae42dc1bc.png)
(from: https://github.com/metanorma/iso-15926-6/pull/1#issuecomment-1103680097)

**Comment by ronaldtse** [comment]
Thank you @maxirmx , it worked!

```sh
$ emf2svg images/image1.emf image1.svg
$ ll image1.svg
-rw-r--r--@ 1 me  staff    34K Apr 30 09:08 image1.svg
```

NOTE: This file is actually from https://github.com/metanorma/iso-15926-6/pull/1
