### ISSUE TITLE
Issue using the emf2svg on Ubuntu 18:04

### ISSUE THREAD

**Issue by abunashir** [metanorma/emf2svg-ruby#37]
Hi there, I was trying to use the latest tool chain here - https://github.com/metanorma/bipm-si-brochure/pull/186/files, and came across the following issue:

<img width="1418" alt="Screenshot 2022-10-30 at 13 19 04" src="https://user-images.githubusercontent.com/1220911/198878593-82d83c30-3c0c-4c19-86dc-6ba590268ddc.png">

I also tried to follow the instructions on the readme, and I'm still having some issue to get it working. Any idea what I might be missing here, and how can get it working? Thanks in advance!

**Comment by ronaldtse** [comment]
Thank you @abunashir for reporting this. Looks like your system is missing GLIBC. What system/container are you on?

**Comment by ronaldtse** [comment]
Ping @abunashir if this issue still occurs. Thanks.

**Comment by ronaldtse** [comment]
@maxirmx do you have any idea why this happens?

**Comment by maxirmx** [comment]
We are packaging on GHA ```ubuntu-latest``` which is ```ubuntu 20.xx``` which produces a binary that is not compatible with ```ubuntu 18.xx```
Ubuntu 18 runners are deprecated on GHA.  If want to maintain 18.xx compatibility we shall pull ```ubuntu:focal``` docker image on top of GHA image and package there.   It has to be implemented for all gems with native extensions

**Comment by ronaldtse** [comment]
Understand. Thanks!

**Comment by abunashir** [comment]
> Ping @abunashir if this issue still occurs. Thanks.

Sorry, I overlooked the last message! I was running Ubuntu 18:04, I still have the issue there but the recent version of ubuntu seems to be okay :)

**Comment by abunashir** [comment]
> We are packaging on GHA `ubuntu-latest` which is `ubuntu 20.xx` which produces a binary that is not compatible with `ubuntu 18.xx`
> Ubuntu 18 runners are deprecated on GHA. If want to maintain 18.xx compatibility we shall pull `ubuntu:focal` docker image on top of GHA image and package there. It has to be implemented for all gems with native extensions

That explains the reason, thanks for that.

**Comment by CAMOBAP** [comment]
Catched on packed-mn too https://github.com/metanorma/packed-mn/actions/runs/3425827247/jobs/5707138658

**Comment by ronaldtse** [comment]
@CAMOBAP can we use Ubuntu 20 for packed-mn?

**Comment by CAMOBAP** [comment]
> @CAMOBAP can we use Ubuntu 20 for packed-mn?

I think yes

**Comment by ronaldtse** [comment]
metanorma/packed-mn#183 failed , @maxirmx could you have a look at https://github.com/metanorma/packed-mn/pull/183#issuecomment-1308348893 ? Thanks.

**Comment by maxirmx** [comment]
Ubuntu 18 is EOL
I believe this issue can be closed

**Comment by ronaldtse** [comment]
Thanks @maxirmx !
