### ISSUE TITLE
Build x64-mingw-ucrt version to support Windows Ruby 3.1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/emf2svg-ruby#7]
As per https://github.com/metanorma/isodoc/issues/385 the x64-mingw32 version is not compatible with Ruby 3.1 Windows.

We need to precompile a `x64-mingw-ucrt` version to allow Ruby 3.1 Windows to install this gem.

As described by @maxirmx https://github.com/metanorma/isodoc/issues/385#issuecomment-1067648062

> emf2svg build script explicitly references `MS Visual Studio 2019`  That was/is relevant for `Windows Server 2019` GHA runner
> Now `windows-latest` is `Windows Server 2022` that has `MS Visual Studio 2022`
> That's why build step fails

The value `Visual Studio 2019` is currently hard-coded here:
https://github.com/metanorma/emf2svg-ruby/blob/4d7d99717f1daefba73a18da3b5b5c693f7edc82/lib/emf2svg/recipe.rb#L42

We need to relax that to make this work.

**Comment by maxirmx** [comment]
I doubt that       `... opts << "-GVisual Studio 16 2019" ...`   is required  at all

**Comment by maxirmx** [comment]
Windows 2022 support looks like a total disaster :  https://github.com/metanorma/libemf2svg/issues/21
