### ISSUE TITLE
Compile Linux arm64 version

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/emf2svg-ruby#9]
- https://github.com/metanorma/metanorma-docker/runs/5560998536?check_suite_focus=true

**Comment by maxirmx** [comment]
IMHO we cannot just cross-compile.  libemf2svg requires freetype, fontconfig and libpng so we will need versions suitable for cross-link. Fontconfig has its own dependencies that will be required recursively.
I would rather try using qemu to pretend that we are using native aarch64

**Comment by CAMOBAP** [comment]
You are right, the solution above will not do dependency resolution for us, so it will be nice to make vcpgk work on top of cross-compile solution from `expressir` (if this is possible at all)

Because the solution that used in expressir 100% based on docker containers, it's allow you to troubleshoot it locally

**Comment by ronaldtse** [comment]
@maxirmx agree with the qemu approach.
